[log]
level = "info"
[labels]
dc = "dc1"
[replication]
enable-placement-rules = true
isolation-level = "dc"
location-labels = ["dc"]
max-replicas = 2
[replication-mode]
replication-mode = "even-replicas"
[replication-mode.even-replicas]
downgrade-timeout = "20s"
[replication-mode.even-replicas.arbitration]
script = ["/bin/bash", "/usr/local/bin/keepalived_arbiter.sh", "tidb-node1"]
type = "custom-script"
